name: Test manual trigger

env:
  SHOULD_RUN: false

on:
  push:
  workflow_dispatch:
    inputs:
      shouldRun:
        description: 'Should this action run?'
        required: true
        default: "${{ env.SHOULD_RUN }}"
        type: boolean

jobs:
  script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: straker/issue-template-tests/.github/actions/my-action@main
        with:
          token: ${{ inputs.shouldRun }}
