name: Test manual trigger

on:
  push:
  workflow_dispatch:
    inputs:
      shouldRun:
        description: 'Should this action run?'
        required: true
        default: false
        type: boolean

jobs:
  script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: straker/issue-template-tests/.github/actions/my-action@main
        with:
          token: ${{ inputs.shouldRun || false }}
